### ISSUE TITLE
nuget package not found.

### ISSUE THREAD

**Issue by hinsona** [evertec/athmovil-xamarin-sdk#2]
I cannot find the ATH Movil SDK on nuget. I tried in visual studio and directly on nuget website (image below).  I tried several ways to search for it -- is it still on nuget?  If not how do I use this?

As noted in the Installation...

ATH Movil SDK works for Android and iOS so you can add it through Manager NuGet Package. Follow the next instructions

- On the menu bar go to Manage Nuget Package
- On the tab Browser look for ATH Movil SDK
- On the result select ATH Movil SDK and don't forget select latest version
- Press the button Add Package

![image](https://user-images.githubusercontent.com/50926630/134022110-894bb8cf-d532-4dd9-8fb7-10599e8f74b4.png)
![image](https://user-images.githubusercontent.com/50926630/134023162-8be3e4bb-33b3-4850-9cf6-263a1486fe70.png)

**Comment by t4t7** [comment]
Hello

For commercial reasons we haven't upload the SDK in Nuget, for this special occasion please create the package in Visual Studio then integrate the SDK as local package into your project.

Regards

**Comment by hansy-dev** [comment]
Hello

For commercial reasons we haven't upload the SDK in Nuget, for this special occasion please create the package in Visual Studio then integrate the SDK as local package into your project.

Regards

**Comment by hinsona** [comment]
> Hello
> 
> For commercial reasons we haven't upload the SDK in Nuget, for this special occasion please create the package in Visual Studio then integrate the SDK as local package into your project.
> 
> Regards

Alright, thanks. 

The instructions should include the necessary steps to implement your API, having things in it that aren't useful doesn't help.
