### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by hinsona** [evertec/athmovil-xamarin-sdk#3]
I've tried building this on multiple machines, each time with the same conclusion.

It complains that the assemblies MonoAndroid.Version=v10.0 and Xamarin.iOS.Version=v1.0 were not found.

Is something missing from the project? This is from a fresh install of VS 2019.

If possible, please add a build to releases.  Thanks!

![image](https://user-images.githubusercontent.com/50926630/134818119-27b88ebb-5948-4b83-a47e-92ab56ce31cc.png)

**Comment by hinsona** [comment]
Never mind found the DLL in the folder.

**Comment by hinsona** [comment]
The file I found was when it randomly built, but it doesn't always work. I did a work around placing MonoAndroid and Xamarin.iOS in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework without closing VS. Now after closing and trying again it doesn't build.

**Comment by hinsona** [comment]
After compiling the entire project, should there be 3 different DLLs? 
1) A shared DLL  (netstandard)
2) An Android Specific DLL 
3) An iOS specific DLL 

If so could you provide the DLLs since we're having a hard time compiling the project. I seem to only have the netstandard DLL and have been unable to compile since.

**Comment by hinsona** [comment]
Any update on this?

If possible... Please publish a build to github releases for the project. Your published project will not build.

**Comment by hansy-dev** [comment]
Hello

It might be the version of Visual Studio or if you have a different installation path of your Visual Studio. Here is the compiled package, you should add the package as local package into your project then you can start using the library.

The package file is inside the zip file, Github doesn't support the nupkg extension.
[ATHMovil.PurchaseSDK.1.0.0.zip](https://github.com/evertec/athmovil-xamarin-sdk/files/7368517/ATHMovil.PurchaseSDK.1.0.0.zip)

Here you can find a example of local packages
https://www.syncfusion.com/kb/9497/how-to-refer-the-nuget-package-from-local-directory-in-mac

Please let me know if it works.

Regards
